#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tychaia.Website.Views.Feed
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Cassette.Views;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Feed/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Tychaia.Website.ViewModels.BlogIndexViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Feed\Index.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral(@"<?xml version=""1.0"" encoding=""ISO-8859-1"" ?>
<rss version=""2.0"" xmlns:atom=""http://www.w3.org/2005/Atom"">
    <channel>
        <title>Tychaia Devlog</title>
        <link>http://www.tychaia.com</link>
        <atom:link href=""http://www.tychaia.com/feed"" rel=""self"" type=""application/rss+xml"" />
        <description>Tychaia is a procedurally generated, open world action-adventure game.</description>
");


            
            #line 12 "..\..\Views\Feed\Index.cshtml"
 foreach (var post in Model.Posts)
{

            
            #line default
            #line hidden
WriteLiteral("        <item>\r\n            <title>");


            
            #line 15 "..\..\Views\Feed\Index.cshtml"
              Write(post.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n            <guid>http://www.tychaia.com/blog/");


            
            #line 16 "..\..\Views\Feed\Index.cshtml"
                                         Write(post.ID);

            
            #line default
            #line hidden
WriteLiteral("</guid>\r\n            <link>http://www.tychaia.com/blog/");


            
            #line 17 "..\..\Views\Feed\Index.cshtml"
                                         Write(post.ID);

            
            #line default
            #line hidden
WriteLiteral("</link>\r\n            <author>");


            
            #line 18 "..\..\Views\Feed\Index.cshtml"
               Write(post.Author);

            
            #line default
            #line hidden
WriteLiteral("</author>\r\n            <description>\r\n                <![CDATA[\r\n                " +
"");


            
            #line 21 "..\..\Views\Feed\Index.cshtml"
           Write(Html.Raw(post.Content));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ]]>\r\n            </description>\r\n        </item>\r\n");


            
            #line 25 "..\..\Views\Feed\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    </channel>\r\n</rss>\r\n");


        }
    }
}
#pragma warning restore 1591
