#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tychaia.Website.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Cassette.Views;
    
    #line 2 "..\..\Views\Home\Index.cshtml"
    using Tychaia.Website;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Tychaia.Website.ViewModels.BlogIndexViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>What is Tychaia?</h2>\r\n<div class=\"block\">\r\n    <p>\r\n        <i>\"Imagine a " +
"game where the world never ends, the scale is infinite and there\'s always one mo" +
"re quest. Where the game starts with nothing and ends with your death. Welcome t" +
"o Tychaia.\"</i>\r\n    </p>\r\n    <p>\r\n        Tychaia is an isometric open world a" +
"ction-adventure game with a procedurally generated world. Death brings a harsh p" +
"enalty - your entire game world is regenerated, you lose everything.\r\n    </p>\r\n" +
"    <p>\r\n        Tychaia is still in early development.  You can follow\r\n       " +
" the latest developments via:\r\n    </p>\r\n    <ul>\r\n        <li>\r\n            The" +
" <a href=\"http://forums.tigsource.com/index.php?topic=27727.0\">development logs<" +
"/a> on TIGSource.\r\n        </li>\r\n        <li>The <a href=\"https://github.com/ha" +
"ch-que/Tychaia\">development repository</a> on GitHub.</li>\r\n        <li>The <a h" +
"ref=\"http://code.redpointsoftware.com.au/maniphest/view/all/\">task and code revi" +
"ew tracker</a> called Phabricator.</li>\r\n        <li>\r\n            The\r\n        " +
"    <a href=\"https://plus.google.com/communities/111849161186026536208\">Google+<" +
"/a>\r\n            or\r\n            <a href=\"https://www.facebook.com/RedpointSoftw" +
"are\">Facebook</a>\r\n            communities.\r\n        </li>\r\n    </ul>\r\n    <p>Yo" +
"u can also contact the developers directly via:</p>\r\n    <ul>\r\n        <li><a hr" +
"ef=\"http://www.twitter.com/#!/hachque\">James Rhodes</a> on Twitter.</li>\r\n      " +
"  <li><a href=\"http://www.twitter.com/#!/Sabre070\">Josh Harvey</a> on Twitter.</" +
"li>\r\n    </ul>\r\n</div>\r\n<h2>\r\n    Tychaia Devlog\r\n    <span class=\"actions\">(<a " +
"href=\"/feed\">RSS Feed</a>)</span>\r\n</h2>\r\n");


            
            #line 43 "..\..\Views\Home\Index.cshtml"
 foreach (var post in Model.Posts)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"block phame\">\r\n        <div class=\"details\">\r\n            <div cl" +
"ass=\"author\">");


            
            #line 47 "..\..\Views\Home\Index.cshtml"
                           Write(post.Author);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div class=\"date\">");


            
            #line 48 "..\..\Views\Home\Index.cshtml"
                         Write(DateTimeHelper.RenderTimestamp(post.UNIXDatePublished));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n        <h3><a href=\"");


            
            #line 50 "..\..\Views\Home\Index.cshtml"
                Write(post.Uri);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 50 "..\..\Views\Home\Index.cshtml"
                           Write(post.Title);

            
            #line default
            #line hidden
WriteLiteral("</a></h3>\r\n        ");


            
            #line 51 "..\..\Views\Home\Index.cshtml"
   Write(Html.Raw(post.Summary));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 53 "..\..\Views\Home\Index.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
