#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tychaia.Website.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Cassette.Views;
    
    #line 2 "..\..\Views\Home\Index.cshtml"
    using Tychaia.Website;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Tychaia.Website.ViewModels.BlogIndexViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home";


            
            #line default
            #line hidden
WriteLiteral("\n<h2>What is Tychaia?</h2>\n<div class=\"block\">\n    <p>\n        <i>\"Imagine a game" +
" where the world never ends, the scale is infinite and there\'s always one more q" +
"uest. Where the game starts with nothing and ends with your death. Welcome to Ty" +
"chaia.\"</i>\n    </p>\n    <p>\n        Tychaia is an infinite Procedural Death Env" +
"ironment<sup><a href=\"http://gamasutra.com/blogs/LarsDoucet/20131203/206159/On_P" +
"rocedural_Death_Labyrinths.php\">[1]</a></sup> game.\n        The game is set in a" +
"n infinite, procedurally generated world; when you die the entire world is regen" +
"erated and you lose everything you\'ve earnt.\n    </p>\n    <p>\n        Tychaia is" +
" still in early development.  You can follow\n        the latest developments via" +
":\n    </p>\n    <ul>\n        <li>\n            The <a href=\"http://forums.tigsourc" +
"e.com/index.php?topic=27727.0\">development logs</a> on TIGSource.\n        </li>\n" +
"        <li>The <a href=\"https://github.com/hach-que/Tychaia\">development reposi" +
"tory</a> on GitHub.</li>\n        <li>The <a href=\"http://code.redpointsoftware.c" +
"om.au/maniphest/query/all/\">task and code review tracker</a> called Phabricator." +
"</li>\n        <li>\n            The\n            <a href=\"https://plus.google.com/" +
"communities/111849161186026536208\">Google+</a>\n            or\n            <a hre" +
"f=\"https://www.facebook.com/RedpointSoftware\">Facebook</a>\n            communiti" +
"es.\n        </li>\n    </ul>\n    <p>You can also contact the developers directly " +
"via:</p>\n    <ul>\n        <li><a href=\"http://www.twitter.com/#!/hachque\">James " +
"Rhodes</a> on Twitter.</li>\n        <li><a href=\"http://www.twitter.com/#!/Sabre" +
"070\">Josh Harvey</a> on Twitter.</li>\n    </ul>\n</div>\n<h2>\n    Tychaia Devlog\n " +
"   <span class=\"actions\">(<a href=\"/feed\">RSS Feed</a>)</span>\n</h2>\n");


            
            #line 44 "..\..\Views\Home\Index.cshtml"
 foreach (var post in Model.Posts)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"block phame\">\n        <div class=\"details\">\n            <div clas" +
"s=\"author\">");


            
            #line 48 "..\..\Views\Home\Index.cshtml"
                           Write(post.Author);

            
            #line default
            #line hidden
WriteLiteral("</div>\n            <div class=\"date\">");


            
            #line 49 "..\..\Views\Home\Index.cshtml"
                         Write(DateTimeHelper.RenderTimestamp(post.UNIXDatePublished));

            
            #line default
            #line hidden
WriteLiteral("</div>\n        </div>\n        <h3><a href=\"");


            
            #line 51 "..\..\Views\Home\Index.cshtml"
                Write(post.Uri);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 51 "..\..\Views\Home\Index.cshtml"
                           Write(post.Title);

            
            #line default
            #line hidden
WriteLiteral("</a></h3>\n        ");


            
            #line 52 "..\..\Views\Home\Index.cshtml"
   Write(Html.Raw(post.Summary));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n");


            
            #line 54 "..\..\Views\Home\Index.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
