#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tychaia.Website.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Cassette.Views;
    
    #line 2 "..\..\Views\Blog\Index.cshtml"
    using Tychaia.Website;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Tychaia.Website.ViewModels.BlogIndexViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Blog\Index.cshtml"
  
    ViewBag.Title = "Tychaia Devlog";


            
            #line default
            #line hidden
WriteLiteral("\n<h2>\n    Tychaia Devlog\n    <span class=\"actions\">(<a href=\"/feed\">RSS Feed</a>)" +
"</span>\n</h2>\n");


            
            #line 11 "..\..\Views\Blog\Index.cshtml"
 foreach (var post in Model.Posts)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"block phame\">\n        <div class=\"details\">\n            <div clas" +
"s=\"author\">");


            
            #line 15 "..\..\Views\Blog\Index.cshtml"
                           Write(post.Author);

            
            #line default
            #line hidden
WriteLiteral("</div>\n            <div class=\"date\">");


            
            #line 16 "..\..\Views\Blog\Index.cshtml"
                         Write(DateTimeHelper.RenderTimestamp(post.UNIXDatePublished));

            
            #line default
            #line hidden
WriteLiteral("</div>\n        </div>\n        <h3><a href=\"");


            
            #line 18 "..\..\Views\Blog\Index.cshtml"
                Write(post.Uri);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 18 "..\..\Views\Blog\Index.cshtml"
                           Write(post.Title);

            
            #line default
            #line hidden
WriteLiteral("</a></h3>\n        ");


            
            #line 19 "..\..\Views\Blog\Index.cshtml"
   Write(Html.Raw(post.Summary));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n");


            
            #line 21 "..\..\Views\Blog\Index.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
