// 
// This source code is licensed in accordance with the licensing outlined
// on the main Tychaia website (www.tychaia.com).  Changes to the
// license on the website apply retroactively.
// 
using System.ComponentModel;
using System.Drawing;
using System.Runtime.Serialization;

namespace Tychaia.ProceduralGeneration
{
    [DataContract]
    [FlowDesignerMajorCategory(FlowMajorCategory.General)]
    [FlowDesignerCategory(FlowCategory.Output)]
    [FlowDesignerName("Store Result")]
    public class AlgorithmResult : Algorithm<int, int>
    {
        [DataMember]
        [Description("The name to display in interfaces such as Make Me a World.")]
        public string Name { get; set; }

        [DataMember]
        [Description("Whether to display this layer as 2D in the editor.")]
        public bool Layer2D { get; set; }

        [DataMember]
        [Description("Whether this layer should be shown in the Make Me a World website.")]
        public bool ShowInMakeMeAWorld { get; set; }

        [DataMember]
        [Description(
            "Whether this layer should be allowed to be generated by the Make Me a World API (used by Google Maps page)."
            )]
        public bool PermitInMakeMeAWorld { get; set; }

        [DataMember]
        [Description("Whether this layer is the default for Make Me a World.")]
        public bool DefaultForMakeMeAWorld { get; set; }

        [DataMember]
        [Description("Whether this layer is the default for in-game.")]
        public bool DefaultForGame { get; set; }

        public override string[] InputNames
        {
            get { return new[] { "Input" }; }
        }

        public override bool Is2DOnly
        {
            get { return this.Layer2D; }
        }

        public override void ProcessCell(IRuntimeContext context, int[] input, int[] output, long x, long y, long z,
            int i, int j, int k, int width, int height, int depth, int ox, int oy, int oz)
        {
            output[(i + ox) + (j + oy) * width + (k + oz) * width * height] =
                input[(i + ox) + (j + oy) * width + (k + oz) * width * height];
        }

        public override Color GetColorForValue(StorageLayer parent, dynamic value)
        {
            return this.DelegateColorForValueToParent(parent, value);
        }
    }
}