#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tychaia.Website.Views.Download
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Cassette.Views;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Download/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Tychaia.Website.ViewModels.DownloadViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Download\Index.cshtml"
  
    ViewBag.Title = "Download Pre-Alpha";


            
            #line default
            #line hidden
WriteLiteral(@"
<h2>Pre-Alpha Downloads</h2>
<div class=""block"">
    <p>
        Tychaia is still in early development.  The builds we provide should be expected
        to be buggy and in some cases, just not work at all.
    </p>
</div>
<h2>Download from Build Server</h2>
<div class=""block"">
");


            
            #line 15 "..\..\Views\Download\Index.cshtml"
     if (Model.BuildServerOnline)
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>\r\n            You can download the latest builds below:\r\n        </p>\r" +
"\n");



WriteLiteral("        <p class=\"download\">\r\n            <a href=\"http://update.redpointsoftware" +
".com.au/Tychaia-Windows/zip\">\r\n                <img src=\"/Content/download_for_w" +
"indows.png\" /> Download Pre-Alpha for Windows\r\n            </a>\r\n        </p>\r\n");



WriteLiteral("        <p class=\"download\">\r\n            <a href=\"http://update.redpointsoftware" +
".com.au/Tychaia-Linux/zip\">\r\n                <img src=\"/Content/download_for_lin" +
"ux.png\" /> Download Pre-Alpha for Linux\r\n            </a>\r\n        </p>\r\n");


            
            #line 30 "..\..\Views\Download\Index.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>\r\n            The build server is currently offline.  If you wish, you" +
" can build a copy of\r\n            Tychaia by downloading the source code from <a" +
" href=\"https://github.com/hach-que/Tychaia\">GitHub</a>.\r\n        </p>\r\n");


            
            #line 37 "..\..\Views\Download\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral(@"</div>
<h2>What happens after Pre-Alpha?</h2>
<div class=""block"">
    <p>
        The plan is that when we hit Alpha (expected Dec 2013), the above links will go away,
        and the price for the game will be set at $7.
    </p>
    <p>
        We'll initially be selling the game through this website, but hope to make the game
        available at various digital distribution sites once the game reaches Beta.
    </p>
    <p>
        <em>This is subject to change without notice.</em>
    </p>
</div>");


        }
    }
}
#pragma warning restore 1591
