#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tychaia.Website.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\_Layout.cshtml"
    using Cassette.Views;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Shared\_Layout.cshtml"
    using Tychaia.Website;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Shared\_Layout.cshtml"
  
    try
    {
        Bundles.Reference("Content");
        Bundles.Reference("Scripts");
    }
    catch (System.NullReferenceException)
    {
        // This crashes under unit tests.
    }


            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html>\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\r\n<head" +
">\r\n    <title>Tychaia - ");


            
            #line 17 "..\..\Views\Shared\_Layout.cshtml"
                Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    ");


            
            #line 18 "..\..\Views\Shared\_Layout.cshtml"
Write(Bundles.RenderStylesheets());

            
            #line default
            #line hidden
WriteLiteral(@"
    <meta name=""description"" content=""Tychaia is an infinite, procedurally generated RPG."">
    <meta name=""author"" content=""Redpoint Software"">
    <meta charset=""UTF-8"" />
</head>
<body>
    <div id=""container"">
        <div id=""header"">
            <h1>
                Tychaia
            </h1>
        </div>
        <div id=""navigation"">
            <ul>
                ");


            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.MenuItem("Home", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 33 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.MenuItem("Download Pre-Alpha", "Index", "Download"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 34 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.MenuItem("Development Wiki", "Index", "Wiki"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <li><a href=\"http://makemeaworld.com/\" target=\"_blank\">Make me " +
"a World!</a></li>\r\n            </ul>\r\n        </div>\r\n        ");


            
            #line 38 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div id=\"footer\">\r\n             &#169; <a href=\"http://www.redpointsoft" +
"ware.com.au/\">Redpoint Software</a> ");


            
            #line 40 "..\..\Views\Shared\_Layout.cshtml"
                                                                                   Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    ");


            
            #line 43 "..\..\Views\Shared\_Layout.cshtml"
Write(Bundles.RenderScripts());

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
